### ISSUE TITLE
Domande gaggi

### ISSUE THREAD

**Issue by Aletrevi** [MatteoSinigaglia/MyCandies#87]
La modularizzazione delle pagine viene valutata positivamente?

**Comment by Aletrevi** [comment]
C'è un modo per validare i tag php?

**Comment by Aletrevi** [comment]
Tag php auto chiusi (autocontenuti)?

**Comment by Aletrevi** [comment]
Tag php non validano nel validatore in qualche modo?

**Comment by Aletrevi** [comment]
Abbiamo nascosto molti bottoni nel css di stampa (es inserimentoCaratteristiche_dashboard.html), va bene?

**Comment by Aletrevi** [comment]
immagini nel suDiNoi si o no??

**Comment by Aletrevi** [comment]
Accedi nella stampa dei form di formCliente?

**Comment by Aletrevi** [comment]
Come aggiungere alt su immagini caricate da php?

**Comment by Aletrevi** [comment]
Alt sensati sulle immagini di pagina 404 e home

**Comment by danielcontro** [comment]
Link finti per evitare riferimenti circolari non indicano se è già stata visitata la pagina, va bene? (Bottone accedi in pagina di login)

**Comment by MatteoSinigaglia** [comment]
> Link finti per evitare riferimenti circolari non indicano se è già stata visitata la pagina, va bene? (Bottone accedi in pagina di login)

Io lo toglierei proprio da quella pagina
