### ISSUE TITLE
controllare se c'è il controllo di max 255 caratteri nella descrizione prodotto

### ISSUE THREAD

**Issue by Aletrevi** [MatteoSinigaglia/MyCandies#94]
Eliminato maxlenght ="255" in 
<span><textarea id="productDescription" name="productDescription" rows="5" cols="40" maxlenght="255"></textarea></span>

in inserisciProdotto_dashboard.html

**Comment by MatteoSinigaglia** [comment]
messo il controllo, per testarlo devo aspettare che il login funzioni

**Comment by MatteoSinigaglia** [comment]
il db non ha scazzi, non serve
