### ISSUE TITLE
rifare css stampa formCliente 

### ISSUE THREAD

**Issue by Aletrevi** [MatteoSinigaglia/MyCandies#96]

**Comment by strang3nt** [comment]
Iscrizione dell'utente al sito e visualizzazione dell'utente iscritto dei dati personali

**Comment by MatteoSinigaglia** [comment]
Cosa c'è da rifare?

**Comment by MatteoSinigaglia** [comment]
Non capisco la domanda nel titolo della issue

**Comment by MatteoSinigaglia** [comment]
sistemato footer, mancano i placeholder
