### ISSUE TITLE
Aggiungere controlli di sintassi su insertcharacteristics.php

### ISSUE THREAD

**Issue by Aletrevi** [MatteoSinigaglia/MyCandies#98]
Ho inserito un principio attivo di nome "111111111111" senza alcun checkbox selezionato e viene aggiunto (dal messaggio che esce in seguito). Controllare anche tutti gli altri form della stessa pagina

**Comment by strang3nt** [comment]
Potrei voler inserire un principio attivo 11111 INVECE ho aggiunto il controllo se vengono selezionati checkbox 
2d3dcc3
